import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./reset.css"
import "./globals.css";
import Header from "./_components/Header/Header";
import LanguageSelector from "./_components/Header/LanguageSelector/LanguageSelector";
import { cookies } from "next/headers";
import { TAppLanguage } from "./_types/types";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const appLanguage = await cookies().get("app-language")?.value as TAppLanguage

  return (
    <html lang={appLanguage}>
      <body className={inter.className}>
        <Header appLanguageCookie={appLanguage}>
          <Link href={`/${appLanguage}/my-vocabulary`}>my vocabulary</Link>
          <Link href={`/${appLanguage}/auth/login`}>login</Link>
          <LanguageSelector />
        </Header>
        {children}
      </body>
    </html>
  );
}
